name: build-mac

on:
  push:
    branches:
      - "*"

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Install build deps
        run: |
          brew install sdl2 cfitsio libnova gsl zlib libusb jpeg libtiff fftw

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'indi'
          repository: 'indilib/indi'

      - name: Build indi
        run: |
          mkdir build_indi
          cd build_indi
          cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=RelWithDebInfo ../indi
          make
          sudo make install

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: 'indi_gamepad'

      - name: Build indi_gamepad
        run: |
          mkdir build_indi_gamepad
          cd build_indi_gamepad
          cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=RelWithDebInfo ../indi_gamepad
          make
      - uses: actions/upload-artifact@v2
        with:
          name: mac-artifact
          path: |
            build_indi_gamepad/indi_gamepad
            build_indi_gamepad/indi_gamepad.xml
