name: build-mac

on:
  push:
    branches:
      - "*"

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        path: 'indi'
        repository: 'indilib/indi'

      - name: Build indi
        run: |
          mkdir build_indi
          cd build_indi
          cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=RelWithDebInfo ../indi
          make
          sudo make install

      - name: Install SDL2
        run: |
          brew install sdl2

      - name: Checkout
        uses: actions/checkout@v2
        path: 'indi_gamepad'

      - name: Build indi_gamepad
        run: |
          mkdir build_indi_gamepad
          cd build_indi_gamepad
          cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DCMAKE_BUILD_TYPE=RelWithDebInfo ../indi_gamepad
          make
